### ISSUE TITLE
Name change for template.conf

### ISSUE THREAD

**Issue by emk2203** [phirecc/mlvd#3]
Could `template.conf` be renamed to `mlvd.conf`? This is quite standard, for example with `mpv` (`.config/mpv/mpv.conf`) or `conky` (`.config/conky/conky.conf`).

This makes it much easier to search for the config file in case one forgets the name.

**Comment by phirecc** [comment]
`template.conf` lives in `/var/lib/mlvd`, so it should be clear that it belongs to `mlvd`. The generated WireGuard config is written to `/etc/wireguard/mlvd.conf`.
I find `template.conf` more descriptive since it is a template from which a WireGuard config is generated.
